# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-03 13:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 3, 13, 11, 20, 393967, tzinfo=utc)),
        ),
    ]
